name: seismic_source_model
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - archspec=0.2.3
  - asciitree=0.3.3
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - black=24.10.0
  - blosc=1.21.6
  - bokeh=3.5.2
  - boltons=24.0.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfitsio=4.4.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - configargparse=1.7
  - contourpy=1.3.0
  - coverage=7.6.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.10.0
  - dask-core=2024.10.0
  - dask-expr=1.1.16
  - distributed=2024.10.0
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - expat=2.6.3
  - fasteners=0.17.3
  - flox=0.9.12
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozendict=2.4.4
  - fsspec=2024.9.0
  - gdal=3.9.2
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.12.2
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - iniconfig=2.0.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.9
  - libmambapy=1.5.9
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsolv=0.7.30
  - libspatialite=5.1.0
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.2
  - menuinst=2.1.2
  - minizip=4.0.7
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - networkx=3.3
  - nspr=4.35
  - nss=3.104
  - numba=0.60.0
  - numcodecs=0.13.0
  - numpy=2.0.2
  - numpy_groupies=0.11.2
  - openjpeg=2.5.2
  - openssl=3.4.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - partd=1.4.2
  - pathspec=0.12.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - proj=9.5.0
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pyogrio=0.9.0
  - pyparsing=3.1.4
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pytest=8.3.3
  - pytest-cov=5.0.0
  - python=3.11.10
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - rasterio=1.3.11
  - re2=2023.09.01
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - rioxarray=0.17.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.4.17
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=73.0.1
  - shapely=2.0.6
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - spdlog=1.13.0
  - sqlite=3.46.1
  - tblib=3.0.0
  - threadpoolctl=3.5.0
  - tiledb=2.25.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - truststore=0.9.2
  - tzcode=2024b
  - tzdata=2024a
  - uriparser=0.9.8
  - urllib3=2.2.3
  - wheel=0.44.0
  - xarray=2025.1.2
  - xarray-datatree=0.0.14
  - xarray-einstats=0.6.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zarr=2.18.3
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
