# Example configuration file to parse raw input files to the correct .h5 format required for the seismic source model.

paths:
  # path to directory for raw input files
  in_path: &in_path ./inputfiles/
  # path to directory for parsed input files
  out_path: &out_path ./

  # external (raw) input files
  raw_fault_file: &raw_fault_file [ *in_path, Faultdata_Groniningen.sqlite3 ]
  raw_press_file: &raw_press_file [ *in_path, ReservoirModel_pressures_V1_2023.csv ]
  raw_compr_file: &raw_compr_file [ *in_path, ReservoirModel_compressibility.csv ]
  raw_eq_file: &raw_eq_file [ *in_path, Earthquake_catalogue_01-12-2023.csv ]

  # reservoir polygon file (for spatial filtering of EQ catalogue)
  calibration_polygon_file: &calibration_polygon_file [ *in_path, Groningen_field_outline.csv ]

  # parsed input files
  eq_file: &eq_file [ *out_path, eq_cat.h5 ]
  fault_file: &fault_file [ *out_path, fault_data.h5 ]
  press_file: &press_file [ *out_path, pressure_grid.h5 ]
  compr_file: &compr_file [ *out_path, compressibility_grid.h5 ]

data_stores:
  eq_catalogue: &eq_catalogue
    type: xarray_dataset
    path: *eq_file

  fault_data: &fault_data
    type: xarray_dataset
    path: *fault_file

  pressure_data: &pressure_data
    type: xarray_dataarray
    path: *press_file

  compressibility_data: &compressibility_data
    type: xarray_dataarray
    path: *compr_file

modules:
  parse_input_ssm:
    data_sources:
      raw_fault_file: *raw_fault_file
      raw_press_file: *raw_press_file
      raw_compr_file: *raw_compr_file
      raw_eq_file: *raw_eq_file
      calibration_polygon_file: *calibration_polygon_file

    data_sinks:
      eq_catalogue: *eq_catalogue
      fault_data: *fault_data
      pressure_data: *pressure_data
      compressibility_data: *compressibility_data

    # eq catalogue temporal range of interest: in yyyymmdd
    calibration_date_range: [ 19950101, 20230228 ]
